---
# ACI EPG playbook
- name: Create Gamma Application EPG and dependencies
  hosts: apic
  connection: local

  vars:
    prechange_file: dryrun.json
    change_file: liverun.json
    tenant: ansible
    vrf: demo

  tasks:
    - name: Create Bridge Domain and dependencies
      ansible.builtin.import_tasks: tasks/bd.yaml
      vars:
        bd: gamma-app
        description: Gamma Application Servers
        gateway: 10.1.103.33
        mask: 27
        scope: public
        l3outs:
          - core

    - name: Create Application Profile and dependencies
      ansible.builtin.import_tasks: tasks/ap.yaml
      vars:
        ap: gamma
        description: Gamma Application Suite

    - name: Create Endpoint Group and dependencies
      ansible.builtin.import_tasks: tasks/epg.yaml
      vars:
        ap: gamma
        epg: app
        alias: Gamma-Application-Servers
        description: Application servers for the Gamma application suite
        bd: gamma-app
        vmm_domain: hx-sc-dvs
        contracts:
          - {contract: gamma-db:mysql, direction: consumer}
          - {contract: gamma-app:app, direction: provider}

    - name: Create Contract and dependencies
      ansible.builtin.import_tasks: tasks/contract.yaml
      vars:
        contract: gamma-app:app
        alias: Gamma-Application.Application
        description: Gamma Application EPG - Application port tcp 1972
        filters:
          - icmp
          - https
          - tcp-1972
